templates:
  - name: "Feature Request"
    description: "Suggest a new feature"
    labels:
      - "enhancement"
    body:
      - type: markdown
        attributes:
          value: |
            Please fill out the sections below to help us with your feature request.
      - type: textarea
        id: problem
        attributes:
          label: "Is your feature request related to a problem? Please describe it."
          placeholder: "A clear and concise description of the problem. For example: I get frustrated when ..."
        validations:
          required: true
      - type: textarea
        id: solution
        attributes:
          label: "Describe the solution you would like"
          placeholder: "A clear and concise description of the solution you envision."
        validations:
          required: true
      - type: textarea
        id: alternatives
        attributes:
          label: "Describe any alternatives you have considered"
          placeholder: "A clear and concise description of any alternative solutions or features you have considered."
      - type: textarea
        id: context
        attributes:
          label: "Additional Context"
          placeholder: "Add any additional context or screenshots to support your feature request."
      - type: markdown
        attributes:
          value: |
            Thank you for your feature request! We will get back to you shortly to discuss it further.
